#!/bin/dash

set -e

buildMode="$1"
buildDirectory="Build"
appBundleName="Countdown"
appBundlePath="$buildDirectory/$appBundleName.app"
signingIdentity="S4H58CCV6D"

clang-format -i Source/*.m Source/*.h

rm -rf "$buildDirectory"
mkdir -p "$appBundlePath/Contents/MacOS"
mkdir -p "$appBundlePath/Contents/Resources/en.lproj"

plutil \
	-convert binary1 \
	-o "$appBundlePath/Contents/Info.plist" \
	"Data/Info.json"

plutil -convert binary1 \
	-o "$appBundlePath/Contents/Resources/en.lproj/InfoPlist.strings" \
	"Data/InfoPlist.json"

set -- \
	-fmodules -fobjc-arc \
	-W \
	-Wall \
	-Wextra \
	-Wpedantic \
	-Wconversion \
	-Wimplicit-fallthrough \
	-Wmissing-prototypes \
	-Wshadow \
	-Wstrict-prototypes

if [ "$buildMode" = "--release" ]; then
	set -- "$@" -Os -fwrapv -ftrivial-auto-var-init=zero -fno-strict-aliasing
else
	set -- "$@" -g -fsanitize=undefined
fi

set -- "$@" -o "$appBundlePath/Contents/MacOS/$appBundleName"
set -- "$@" "Source/EntryPoint.m"

clang "$@"

temporaryEntitlementsPath="$buildDirectory/$appBundleName.entitlements"
plutil \
	-convert xml1 \
	-o "$temporaryEntitlementsPath" \
	"Data/Entitlements.json"

if [ "$buildMode" != "--release" ]; then
	plutil \
		-insert "com\.apple\.security\.get-task-allow" -bool YES \
		"$temporaryEntitlementsPath"
fi

if [ "$buildMode" = "--release" ]; then
	set -- --sign "$signingIdentity" --timestamp
else
	set -- --sign -
fi

set -- "$@" \
	--entitlements "$temporaryEntitlementsPath" \
	--options runtime "$appBundlePath/Contents/MacOS/$appBundleName"

codesign "$@"

rm "$temporaryEntitlementsPath"

if [ "$buildMode" = "--release" ]; then
	ditto \
		-c -k --keepParent \
		"$appBundlePath" \
		"$buildDirectory/$appBundleName.zip"

	xcrun notarytool submit \
		"$buildDirectory/$appBundleName.zip" \
		--keychain-profile notarytool-password \
		--wait

	stapler staple "$appBundlePath"
	syspolicy_check distribution "$appBundlePath"

	aa archive -D "$appBundlePath" -o "Build/$appBundleName.aar"
fi
